# Generated by Django 4.1.3 on 2023-02-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("isActive", models.BooleanField()),
            ],
        ),
    ]
