# Generated by Django 4.1.3 on 2023-02-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
