# Generated by Django 4.1.3 on 2023-02-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_uploadmodel_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(default="", upload_to="images"),
        ),
    ]
